server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.ci6saqbza9gi.ap-northeast-2.rds.amazonaws.com:3306/blog
    #url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul
    username: HB
    password: fshad4733
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      "[hibernate.format_sql]": true

  h2:
    console:
      enabled: true

  jackson:
    serialization:
      fail-on-empty-beans: false
  
  security:
    oauth2:
      client:
        registration:
          google: 
            client-id: 94482621989-4jrirreivca1c7kgcbgvqae884cj8913.apps.googleusercontent.com
            client-secret: 8Vom8ZbWqMJnUZWk6XOX_6Cr
            scope:
            - email
            - profile
          
          facebook: 
            client-id: 466532757764702
            client-secret: 7d1882a100b0ab92b8e7bf39a66be065
            scope:
            - email
            - public_profile          
          
          naver: 
            client-id: MwdMDU2e3EnSvwD4eok_
            client-secret: MJe2TdT2pY
            scope:
            - name
            - email
            - profile_image
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
          
        provider:
          naver: 
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회원정보를 json으로 받는데 response라는 키값으로 네이버가 리턴해줌

cos:
  key: ad4733